## Andere Datenquellen

Es ist auch m√∂glich andere Quellen als nur CSV zu benutzen (z.B.: SQL oder JSON auch in Kombination mit einer API)

In [1]:
import pandas as pd
import requests as api

In [3]:
json = api.get("https://open.er-api.com/v6/latest/USD")

In [5]:
json.json()

{'result': 'success',
 'provider': 'https://www.exchangerate-api.com',
 'documentation': 'https://www.exchangerate-api.com/docs/free',
 'terms_of_use': 'https://www.exchangerate-api.com/terms',
 'time_last_update_unix': 1680048151,
 'time_last_update_utc': 'Wed, 29 Mar 2023 00:02:31 +0000',
 'time_next_update_unix': 1680135741,
 'time_next_update_utc': 'Thu, 30 Mar 2023 00:22:21 +0000',
 'time_eol_unix': 0,
 'base_code': 'USD',
 'rates': {'USD': 1,
  'AED': 3.6725,
  'AFN': 86.730865,
  'ALL': 105.371549,
  'AMD': 388.46387,
  'ANG': 1.79,
  'AOA': 511.278286,
  'ARS': 207.299483,
  'AUD': 1.493258,
  'AWG': 1.79,
  'AZN': 1.699985,
  'BAM': 1.804845,
  'BBD': 2,
  'BDT': 106.844712,
  'BGN': 1.804764,
  'BHD': 0.376,
  'BIF': 2072.552996,
  'BMD': 1,
  'BND': 1.327793,
  'BOB': 6.914887,
  'BRL': 5.188376,
  'BSD': 1,
  'BTN': 82.246557,
  'BWP': 13.214049,
  'BYN': 2.638271,
  'BZD': 2,
  'CAD': 1.361837,
  'CDF': 2052.743926,
  'CHF': 0.919838,
  'CLP': 805.571134,
  'CNY': 6.878564,
  'COP': 4652.776038,
  'CRC': 542.55267,
  'CUP': 24,
  'CVE': 101.752805,
  'CZK': 21.841831,
  'DJF': 177.721,
  'DKK': 6.884456,
  'DOP': 54.794822,
  'DZD': 135.699701,
  'EGP': 30.864471,
  'ERN': 15,
  'ETB': 53.90716,
  'EUR': 0.923016,
  'FJD': 2.203322,
  'FKP': 0.810996,
  'FOK': 6.884456,
  'GBP': 0.811056,
  'GEL': 2.571862,
  'GGP': 0.810996,
  'GHS': 11.955299,
  'GIP': 0.810996,
  'GMD': 63.65695,
  'GNF': 8508.363432,
  'GTQ': 7.789044,
  'GYD': 211.061486,
  'HKD': 7.849877,
  'HNL': 24.623949,
  'HRK': 6.952855,
  'HTG': 155.000393,
  'HUF': 352.450828,
  'IDR': 15095.26891,
  'ILS': 3.547651,
  'IMP': 0.810996,
  'INR': 82.246651,
  'IQD': 1311.096924,
  'IRR': 42100.465496,
  'ISK': 137.21508,
  'JEP': 0.810996,
  'JMD': 150.91097,
  'JOD': 0.709,
  'JPY': 130.939475,
  'KES': 131.617806,
  'KGS': 87.616463,
  'KHR': 4082.954309,
  'KID': 1.493396,
  'KMF': 453.989013,
  'KRW': 1297.40961,
  'KWD': 0.306201,
  'KYD': 0.833333,
  'KZT': 454.823759,
  'LAK': 16978.468758,
  'LBP': 15000,
  'LKR': 321.942276,
  'LRD': 162.482369,
  'LSL': 18.156648,
  'LYD': 4.790967,
  'MAD': 10.243863,
  'MDL': 18.453297,
  'MGA': 4315.136417,
  'MKD': 57.266771,
  'MMK': 2096.676827,
  'MNT': 3520.249126,
  'MOP': 8.085334,
  'MRU': 34.251179,
  'MUR': 46.002651,
  'MVR': 15.43563,
  'MWK': 1029.654686,
  'MXN': 18.250299,
  'MYR': 4.401533,
  'MZN': 64.050721,
  'NAD': 18.156648,
  'NGN': 460.922911,
  'NIO': 36.520366,
  'NOK': 10.395059,
  'NPR': 131.594491,
  'NZD': 1.601507,
  'OMR': 0.384497,
  'PAB': 1,
  'PEN': 3.769606,
  'PGK': 3.519228,
  'PHP': 54.327093,
  'PKR': 283.35165,
  'PLN': 4.319098,
  'PYG': 7139.494709,
  'QAR': 3.64,
  'RON': 4.571822,
  'RSD': 108.297783,
  'RUB': 76.568611,
  'RWF': 1133.291824,
  'SAR': 3.75,
  'SBD': 8.501793,
  'SCR': 13.084656,
  'SDG': 534.973574,
  'SEK': 10.356022,
  'SGD': 1.327936,
  'SHP': 0.810996,
  'SLE': 21.380921,
  'SLL': 21380.9209,
  'SOS': 568.189604,
  'SRD': 35.888621,
  'SSP': 859.826604,
  'STN': 22.608658,
  'SYP': 2509.968381,
  'SZL': 18.156648,
  'THB': 34.243756,
  'TJS': 10.907013,
  'TMT': 3.49995,
  'TND': 3.086085,
  'TOP': 2.361028,
  'TRY': 19.117553,
  'TTD': 6.773206,
  'TVD': 1.493396,
  'TWD': 30.27359,
  'TZS': 2338.634023,
  'UAH': 36.926934,
  'UGX': 3785.694085,
  'UYU': 38.928847,
  'UZS': 11413.621606,
  'VES': 24.4151,
  'VND': 23500.002528,
  'VUV': 118.757333,
  'WST': 2.727867,
  'XAF': 605.318684,
  'XCD': 2.7,
  'XDR': 0.743653,
  'XOF': 605.318684,
  'XPF': 110.119854,
  'YER': 250.080385,
  'ZAR': 18.15866,
  'ZMW': 21.243101,
  'ZWL': 916.726493}}

In [9]:
json.json()["rates"]

{'USD': 1,
 'AED': 3.6725,
 'AFN': 86.730865,
 'ALL': 105.371549,
 'AMD': 388.46387,
 'ANG': 1.79,
 'AOA': 511.278286,
 'ARS': 207.299483,
 'AUD': 1.493258,
 'AWG': 1.79,
 'AZN': 1.699985,
 'BAM': 1.804845,
 'BBD': 2,
 'BDT': 106.844712,
 'BGN': 1.804764,
 'BHD': 0.376,
 'BIF': 2072.552996,
 'BMD': 1,
 'BND': 1.327793,
 'BOB': 6.914887,
 'BRL': 5.188376,
 'BSD': 1,
 'BTN': 82.246557,
 'BWP': 13.214049,
 'BYN': 2.638271,
 'BZD': 2,
 'CAD': 1.361837,
 'CDF': 2052.743926,
 'CHF': 0.919838,
 'CLP': 805.571134,
 'CNY': 6.878564,
 'COP': 4652.776038,
 'CRC': 542.55267,
 'CUP': 24,
 'CVE': 101.752805,
 'CZK': 21.841831,
 'DJF': 177.721,
 'DKK': 6.884456,
 'DOP': 54.794822,
 'DZD': 135.699701,
 'EGP': 30.864471,
 'ERN': 15,
 'ETB': 53.90716,
 'EUR': 0.923016,
 'FJD': 2.203322,
 'FKP': 0.810996,
 'FOK': 6.884456,
 'GBP': 0.811056,
 'GEL': 2.571862,
 'GGP': 0.810996,
 'GHS': 11.955299,
 'GIP': 0.810996,
 'GMD': 63.65695,
 'GNF': 8508.363432,
 'GTQ': 7.789044,
 'GYD': 211.061486,
 'HKD': 7.849877,
 'HNL': 24.623949,
 'HRK': 6.952855,
 'HTG': 155.000393,
 'HUF': 352.450828,
 'IDR': 15095.26891,
 'ILS': 3.547651,
 'IMP': 0.810996,
 'INR': 82.246651,
 'IQD': 1311.096924,
 'IRR': 42100.465496,
 'ISK': 137.21508,
 'JEP': 0.810996,
 'JMD': 150.91097,
 'JOD': 0.709,
 'JPY': 130.939475,
 'KES': 131.617806,
 'KGS': 87.616463,
 'KHR': 4082.954309,
 'KID': 1.493396,
 'KMF': 453.989013,
 'KRW': 1297.40961,
 'KWD': 0.306201,
 'KYD': 0.833333,
 'KZT': 454.823759,
 'LAK': 16978.468758,
 'LBP': 15000,
 'LKR': 321.942276,
 'LRD': 162.482369,
 'LSL': 18.156648,
 'LYD': 4.790967,
 'MAD': 10.243863,
 'MDL': 18.453297,
 'MGA': 4315.136417,
 'MKD': 57.266771,
 'MMK': 2096.676827,
 'MNT': 3520.249126,
 'MOP': 8.085334,
 'MRU': 34.251179,
 'MUR': 46.002651,
 'MVR': 15.43563,
 'MWK': 1029.654686,
 'MXN': 18.250299,
 'MYR': 4.401533,
 'MZN': 64.050721,
 'NAD': 18.156648,
 'NGN': 460.922911,
 'NIO': 36.520366,
 'NOK': 10.395059,
 'NPR': 131.594491,
 'NZD': 1.601507,
 'OMR': 0.384497,
 'PAB': 1,
 'PEN': 3.769606,
 'PGK': 3.519228,
 'PHP': 54.327093,
 'PKR': 283.35165,
 'PLN': 4.319098,
 'PYG': 7139.494709,
 'QAR': 3.64,
 'RON': 4.571822,
 'RSD': 108.297783,
 'RUB': 76.568611,
 'RWF': 1133.291824,
 'SAR': 3.75,
 'SBD': 8.501793,
 'SCR': 13.084656,
 'SDG': 534.973574,
 'SEK': 10.356022,
 'SGD': 1.327936,
 'SHP': 0.810996,
 'SLE': 21.380921,
 'SLL': 21380.9209,
 'SOS': 568.189604,
 'SRD': 35.888621,
 'SSP': 859.826604,
 'STN': 22.608658,
 'SYP': 2509.968381,
 'SZL': 18.156648,
 'THB': 34.243756,
 'TJS': 10.907013,
 'TMT': 3.49995,
 'TND': 3.086085,
 'TOP': 2.361028,
 'TRY': 19.117553,
 'TTD': 6.773206,
 'TVD': 1.493396,
 'TWD': 30.27359,
 'TZS': 2338.634023,
 'UAH': 36.926934,
 'UGX': 3785.694085,
 'UYU': 38.928847,
 'UZS': 11413.621606,
 'VES': 24.4151,
 'VND': 23500.002528,
 'VUV': 118.757333,
 'WST': 2.727867,
 'XAF': 605.318684,
 'XCD': 2.7,
 'XDR': 0.743653,
 'XOF': 605.318684,
 'XPF': 110.119854,
 'YER': 250.080385,
 'ZAR': 18.15866,
 'ZMW': 21.243101,
 'ZWL': 916.726493}

In [4]:
readJson = pd.DataFrame.from_dict(json.json()["rates"], orient="index")

In [5]:
readJson

              0
USD    1.000000
AED    3.672500
AFN   86.730865
ALL  105.371549
AMD  388.463870
..          ...
XPF  110.119854
YER  250.080385
ZAR   18.158660
ZMW   21.243101
ZWL  916.726493

[162 rows x 1 columns]

In [6]:
readJson = readJson.rename(columns={0: "Exchange Rate"})

In [14]:
readJson

     Exchange Rate
USD       1.000000
AED       3.672500
AFN      86.730865
ALL     105.371549
AMD     388.463870
..             ...
XPF     110.119854
YER     250.080385
ZAR      18.158660
ZMW      21.243101
ZWL     916.726493

[162 rows x 1 columns]

In [15]:
data = pd.read_json("https://open.er-api.com/v6/latest/USD")

In [16]:
data

,result,provider,documentation,terms_of_use,time_last_update_unix,time_last_update_utc,time_next_update_unix,time_next_update_utc,time_eol_unix,base_code,rates
AED,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1680048151,"Wed, 29 Mar 2023 00:02:31 +0000",1680135741,"Thu, 30 Mar 2023 00:22:21 +0000",0,USD,3.672500
AFN,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1680048151,"Wed, 29 Mar 2023 00:02:31 +0000",1680135741,"Thu, 30 Mar 2023 00:22:21 +0000",0,USD,86.730865
ALL,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1680048151,"Wed, 29 Mar 2023 00:02:31 +0000",1680135741,"Thu, 30 Mar 2023 00:22:21 +0000",0,USD,105.371549
AMD,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1680048151,"Wed, 29 Mar 2023 00:02:31 +0000",1680135741,"Thu, 30 Mar 2023 00:22:21 +0000",0,USD,388.463870
ANG,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1680048151,"Wed, 29 Mar 2023 00:02:31 +0000",1680135741,"Thu, 30 Mar 2023 00:22:21 +0000",0,USD,1.790000
...,...,...,...,...,...,...,...,...,...,...,...
XPF,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1680048151,"Wed, 29 Mar 2023 00:02:31 +0000",1680135741,"Thu, 30 Mar 2023 00:22:21 +0000",0,USD,110.119854
YER,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1680048151,"Wed, 29 Mar 2023 00:02:31 +0000",1680135741,"Thu, 30 Mar 2023 00:22:21 +0000",0,USD,250.080385
ZAR,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1680048151,"Wed, 29 Mar 2023 00:02:31 +0000",1680135741,"Thu, 30 Mar 2023 00:22:21 +0000",0,USD,18.158660
ZMW,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1680048151,"Wed, 29 Mar 2023 00:02:31 +0000",1680135741,"Thu, 30 Mar 2023 00:22:21 +0000",0,USD,21.243101
ZWL,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1680048151,"Wed, 29 Mar 2023 00:02:31 +0000",1680135741,"Thu, 30 Mar 2023 00:22:21 +0000",0,USD,916.726493

## Daten aus einer Datenbank einlesen

In [24]:
import sqlite3 as sql
connection = sql.connect("Test2.db")

cursor = connection.cursor()

cursor.execute("create table test(id integer primary key, name varchar(30))")
cursor.execute("insert into test (id, name) values(1, 'Max1')")
cursor.execute("insert into test (id, name) values(2, 'Max2')")
cursor.execute("insert into test (id, name) values(3, 'Max3')")

data = pd.read_sql("select * from test", con=connection)

In [25]:
data

   id  name
0   1  Max1
1   2  Max2
2   3  Max3

## Export von Daten

DataFrames k√∂nnen in verschiedene Formate konvertiert und gespeichert werden:

In [10]:
import openpyxl
readJson.to_excel("Json.xlsx")

In [7]:
readJson.to_csv("Json.csv")

In [8]:
readJson.to_json("Json.json")